name: Run python tests

on:
  [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies and test
        env:
          kucoin_api_key: ${{ secrets.KUCOIN_TEST_API_KEY }}
          kucoin_api_secret: ${{ secrets.KUCOIN_TEST_API_SECRET }}
          kucoin_api_password: ${{ secrets.KUCOIN_TEST_PASSWORD }}
          mexc_api_key: ${{ secrets.MEXC_TEST_API_KEY }}
          mexc_api_secret: ${{ secrets.MEXC_TEST_API_SECRET }}
          gateio_api_key: ${{ secrets.GATEIO_TEST_API_KEY }}
          gateio_api_secret: ${{ secrets.GATEIO_TEST_API_SECRET }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          touch .test.env
          echo -e "KUCOIN_TEST_API_KEY=$kucoin_api_key \n" >> .test.env
          echo -e "KUCOIN_TEST_API_SECRET=$kucoin_api_secret \n" >> .test.env
          echo -e "KUCOIN_TEST_PASSWORD=$kucoin_api_password \n" >> .test.env
          echo -e "MEXC_TEST_API_KEY=$mexc_api_key \n" >> .test.env
          echo -e "MEXC_TEST_API_SECRET=$mexc_api_secret \n" >> .test.env
          echo -e "GATEIO_TEST_API_KEY=$gateio_api_key \n" >> .test.env
          echo -e "GATEIO_TEST_API_SECRET=$gateio_api_secret \n" >> .test.env
          python -m unittest discover -s tests