name: Run python tests

on:
  [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies and test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover -s tests